'use client';

import { useEffect, useState } from 'react';
import SideBar from '@/components/Shared/SideBar';
import Head from 'next/head';
import { createClient } from '@/utils/supabase/client';

interface Link {
  id: number;
  name: string;
  links: string;
  icon: JSX.Element;
}
const supabase = createClient();

const Layout = (props: { children: JSX.Element }) => {
  const [isUser, setIsUser] = useState(false);

  // useEffect(() => {
  //   const insertData = async () => {
  //     const {
  //       data: { user },
  //     } = await supabase.auth.getUser();

  //     if (user) {
  //       setIsUser(true);
  //     }
  //   };
  //   insertData();
  // }, []);

  return (
    <>
      <Head>
        <title>Nucleus - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/nucleus_favicon.svg" />
      </Head>

      <div className="flex md:h-screen w-screen overflow-hidden bg-[#EAEAEA] dark:bg-[#41395b] p-2">
        <SideBar />
        <div className="flex-1  dark:text-black px-2 md:px-5 py-2 h-full overflow-y-scroll ">
          {props.children}
        </div>
      </div>
    </>
  );
};

export default Layout;
