import Head from 'next/head';
import BillsCard from './BillCard';
import Layout from '@/components/Layout';
import BillSummary from './BillSummary';
import BillGrowth from './BillGrowth';
import Calendar from './Calendar';
import UserLocation from './UserLocation';

const Billing = () => {
  const bills = [
    { title: 'Recent Bills', amount: '$25,000', chart: 'coming soon' },
    { title: 'Paid Bills', amount: '$15,000', chart: 'coming soon' },
  ];
  return (
    <>
      <Head>
        <title>Modern dashboard - Billing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="h-full">
          <header>
            <h1 className="text-3xl font-semibold">Billings</h1>
            <p>Information about your bills</p>
          </header>
          <div className="grid grid-cols-3 gap-2 w-full border py-2">
            <div className="col-span-2 rounded-md w-full ">
              <div className="flex w-full gap-2">
                {bills.map((item, idx) => (
                  <BillsCard billItem={item} key={idx} />
                ))}
              </div>
              <div>
                <BillSummary />
                <BillGrowth />
              </div>
            </div>
            <span className="col-span-1 flex flex-col gap-2 h-full">
              <Calendar />
              <UserLocation />
            </span>
          </div>
        </div>
      </Layout>
    </>
  );
};
export default Billing;
